(ns flares-example
  "Demonstrates Joyride Flares for creating WebView panels and sidebar views"
  (:require [joyride.flare :as flare]))

;; SVG visualization with multiple shapes
(defn create-svg []
  [:svg {:height 200 :width 200 :style {:border "1px" :solid "#ccc"}}
   [:circle {:r 30 :cx 50 :cy 50 :fill "red" :opacity 0.7}]
   [:rect {:x 70 :y 70 :width 60 :height 40 :fill "blue" :opacity 0.7}]
   [:line {:x1 10 :y1 180 :x2 190 :y2 20 :stroke "green" :stroke-width 3}]
   [:text {:x 100 :y 190 :text-anchor "middle" :fill "purple"} "Joyride!"]])

;; Data table example
(defn data-table [data]
  [:table {:style "border-collapse: collapse; width: 100%;"}
   [:thead
    [:tr
     (for [header (keys (first data))]
       [:th {:style "border: 1px solid #ddd; padding: 8px; background: #f2f2f2;"}
        (name header)])]]
   [:tbody
    (for [row data]
      [:tr
       (for [value (vals row)]
         [:td {:style "border: 1px solid #ddd; padding: 8px;"}
          (str value)])])]])

(def sample-data
  [{:name "Alice" :age 30 :city "New York"}
   {:name "Bob" :age 25 :city "San Francisco"}
   {:name "Carol" :age 35 :city "Chicago"}])

;; Fancy animated flare with modern design
;; Yes, ”modern” gives it away, this is generated by Copilot (Sonnet 4)
(defn fancy-flare []
  [:div
   ;; Add CSS animations in a style tag
   [:style "
     @keyframes pulse {
       0% { transform: scale(1); }
       50% { transform: scale(1.05); }
       100% { transform: scale(1); }
     }
     @keyframes float {
       0%, 100% { transform: translateY(0px); }
       50% { transform: translateY(-10px); }
     }
     .pulse { animation: pulse 2s infinite; }
     .float { animation: float 3s ease-in-out infinite; }
     .float-delay { animation: float 3s ease-in-out infinite 0.5s; }
     .float-delay-2 { animation: float 3s ease-in-out infinite 1s; }
   "]

   ;; Main container with style map
   [:div {:style {:font-family "'SF Pro Display', system-ui, sans-serif"
                  :background "linear-gradient(135deg, #667eea 0%, #764ba2 100%)"
                  :color "white"
                  :padding "30px"
                  :border-radius "16px"
                  :min-height "500px"}}

    ;; Header
    [:div {:style {:text-align "center" :margin-bottom "40px"}}
     [:h1 {:class "pulse"
           :style {:font-size "3em"
                   :margin "0"
                   :text-shadow "2px 2px 8px rgba(0,0,0,0.5)"}}
      "✨ Fancy Joyride Flare ✨"]
     [:p {:style {:font-size "1.3em" :opacity "0.9" :margin-top "10px"}}
      "A beautiful, animated HTML experience"]]

    ;; Feature cards
    [:div {:style {:display "flex"
                   :justify-content "space-around"
                   :flex-wrap "wrap"
                   :gap "20px"
                   :margin-bottom "40px"}}

     [:div {:class "float"
            :style {:background "rgba(255,255,255,0.15)"
                    :backdrop-filter "blur(10px)"
                    :border-radius "20px"
                    :padding "25px"
                    :min-width "180px"
                    :text-align "center"
                    :border "1px solid rgba(255,255,255,0.2)"
                    :box-shadow "0 8px 32px rgba(0,0,0,0.1)"}}
      [:div {:style {:font-size "3em" :margin-bottom "15px"}} "🚀"]
      [:h3 {:style {:margin "0 0 10px 0" :font-size "1.4em"}} "Fast"]
      [:p {:style {:margin "0" :opacity "0.8" :font-size "0.95em"}} "Lightning quick rendering"]]

     [:div {:class "float-delay"
            :style {:background "rgba(255,255,255,0.15)"
                    :backdrop-filter "blur(10px)"
                    :border-radius "20px"
                    :padding "25px"
                    :min-width "180px"
                    :text-align "center"
                    :border "1px solid rgba(255,255,255,0.2)"
                    :box-shadow "0 8px 32px rgba(0,0,0,0.1)"}}
      [:div {:style {:font-size "3em" :margin-bottom "15px"}} "⚡"]
      [:h3 {:style {:margin "0 0 10px 0" :font-size "1.4em"}} "Interactive"]
      [:p {:style {:margin "0" :opacity "0.8" :font-size "0.95em"}} "Dynamic and responsive"]]

     [:div {:class "float-delay-2"
            :style {:background "rgba(255,255,255,0.15)"
                    :backdrop-filter "blur(10px)"
                    :border-radius "20px"
                    :padding "25px"
                    :min-width "180px"
                    :text-align "center"
                    :border "1px solid rgba(255,255,255,0.2)"
                    :box-shadow "0 8px 32px rgba(0,0,0,0.1)"}}
      [:div {:style {:font-size "3em" :margin-bottom "15px"}} "🎨"]
      [:h3 {:style {:margin "0 0 10px 0" :font-size "1.4em"}} "Beautiful"]
      [:p {:style {:margin "0" :opacity "0.8" :font-size "0.95em"}} "Modern design language"]]]

    ;; Progress section
    [:div {:style {:margin "40px 0"}}
     [:h3 {:style {:margin-bottom "20px" :font-size "1.3em"}} "🔋 Joyride Power Level"]
     [:div {:style {:background "rgba(255,255,255,0.2)"
                    :border-radius "30px"
                    :height "24px"
                    :overflow "hidden"
                    :position "relative"}}
      [:div {:style {:background "linear-gradient(90deg, #00ff88, #00ccff, #8c52ff)"
                     :height "100%"
                     :width "87%"
                     :border-radius "30px"
                     :box-shadow "0 0 20px rgba(0,255,136,0.4)"}}]]
     [:div {:style {:text-align "right" :margin-top "8px" :font-size "1em" :opacity "0.9"}} "87% Awesome"]]

    ;; Footer
    [:div {:style {:text-align "center"
                   :margin-top "40px"
                   :padding-top "25px"
                   :border-top "1px solid rgba(255,255,255,0.2)"}}
     [:div {:style {:display "flex"
                    :justify-content "center"
                    :align-items "center"
                    :gap "10px"
                    :margin-bottom "15px"}}
      [:span {:style {:font-size "1.5em"}} "❤️"]
      [:span {:style {:font-size "1.1em"}} "Created with Joyride Flares"]
      [:span {:style {:font-size "1.5em"}} "🎉"]]
     [:p {:style {:margin "0" :font-size "0.9em" :opacity "0.7"}}
      (str "Generated at " (.toLocaleTimeString (js/Date.)))]
     [:p {:style {:margin "10px 0 0 0" :font-size "0.85em" :opacity "0.6"}}
      "Interactive ClojureScript in VS Code"]]]])

;; Fancy SVG flare with animations and beautiful graphics
;; Here “beautiful” is the AI-ism revealing who created the example =)
(defn fancy-svg-flare []
  [:div {:style {:background "linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)"
                 :padding "30px"
                 :border-radius "20px"
                 :text-align "center"}}

   [:style "
     @keyframes rotate {
       from { transform: rotate(0deg); }
       to { transform: rotate(360deg); }
     }
     @keyframes pulse-svg {
       0%, 100% { transform: scale(1); opacity: 0.8; }
       50% { transform: scale(1.1); opacity: 1; }
     }
     @keyframes wave {
       0%, 100% { d: path('M0,50 Q25,30 50,50 T100,50'); }
       50% { d: path('M0,50 Q25,70 50,50 T100,50'); }
     }
     .rotating { animation: rotate 8s linear infinite; }
     .pulsing { animation: pulse-svg 3s ease-in-out infinite; }
     .floating { animation: pulse-svg 4s ease-in-out infinite 1s; }
   "]

   [:h2 {:style {:color "white" :margin-bottom "30px" :font-size "2.2em"}} "🎨 Fancy SVG Showcase"]

   [:div {:style {:display "flex" :justify-content "space-around" :flex-wrap "wrap" :gap "30px"}}

    ;; Animated geometric pattern
    [:div {:style {:background "rgba(255,255,255,0.1)" :border-radius "15px" :padding "20px"}}
     [:h3 {:style {:color "white" :margin-bottom "15px"}} "Rotating Geometry"]
     [:svg {:width 200 :height 200 :style {:background "rgba(0,0,0,0.2)" :border-radius "10px"}}
      [:defs
       [:linearGradient {:id "grad1" :x1 "0%" :y1 "0%" :x2 "100%" :y2 "100%"}
        [:stop {:offset "0%" :style {:stop-color "#ff6b6b" :stop-opacity 1}}]
        [:stop {:offset "100%" :style {:stop-color "#4ecdc4" :stop-opacity 1}}]]
       [:radialGradient {:id "grad2" :cx "50%" :cy "50%" :r "50%"}
        [:stop {:offset "0%" :style {:stop-color "#ffe66d" :stop-opacity 1}}]
        [:stop {:offset "100%" :style {:stop-color "#ff6b6b" :stop-opacity 0.8}}]]]

      [:g {:class "rotating" :style {:transform-origin "100px 100px"}}
       [:polygon {:points "100,20 180,80 180,120 100,180 20,120 20,80"
                  :fill "url(#grad1)"
                  :opacity 0.8}]
       [:circle {:cx 100 :cy 100 :r 25 :fill "url(#grad2)"}]]

      [:circle {:cx 100 :cy 100 :r 85 :fill "none" :stroke "#fff" :stroke-width 2 :opacity 0.3}]
      [:circle {:cx 100 :cy 100 :r 65 :fill "none" :stroke "#fff" :stroke-width 1 :opacity 0.2}]]]

    ;; Pulsing data visualization
    [:div {:style {:background "rgba(255,255,255,0.1)" :border-radius "15px" :padding "20px"}}
     [:h3 {:style {:color "white" :margin-bottom "15px"}} "Data Pulse"]
     [:svg {:width 200 :height 200 :style {:background "rgba(0,0,0,0.2)" :border-radius "10px"}}
      [:defs
       [:linearGradient {:id "barGrad" :x1 "0%" :y1 "100%" :x2 "0%" :y2 "0%"}
        [:stop {:offset "0%" :style {:stop-color "#667eea" :stop-opacity 1}}]
        [:stop {:offset "100%" :style {:stop-color "#764ba2" :stop-opacity 1}}]]]

      ;; Animated bars representing data
      (for [i (range 6)]
        [:rect {:key i
                :x (+ 20 (* i 25))
                :y (- 180 (* (inc i) 20))
                :width 20
                :height (* (inc i) 20)
                :fill "url(#barGrad)"
                :class "pulsing"
                :style {:animation-delay (str (* i 0.3) "s")}}])

      ;; Grid lines
      (for [i (range 5)]
        [:line {:key i
                :x1 10 :y1 (+ 40 (* i 30))
                :x2 190 :y2 (+ 40 (* i 30))
                :stroke "#fff"
                :stroke-width 0.5
                :opacity 0.3}])]]

    ;; Organic flowing shapes
    [:div {:style {:background "rgba(255,255,255,0.1)" :border-radius "15px" :padding "20px"}}
     [:h3 {:style {:color "white" :margin-bottom "15px"}} "Organic Flow"]
     [:svg {:width 200 :height 200 :style {:background "rgba(0,0,0,0.2)" :border-radius "10px"}}
      [:defs
       [:linearGradient {:id "flowGrad" :x1 "0%" :y1 "0%" :x2 "100%" :y2 "100%"}
        [:stop {:offset "0%" :style {:stop-color "#00f5ff" :stop-opacity 0.8}}]
        [:stop {:offset "50%" :style {:stop-color "#00bcd4" :stop-opacity 0.6}}]
        [:stop {:offset "100%" :style {:stop-color "#4fc3f7" :stop-opacity 0.8}}]]]

      [:path {:d "M20,100 Q60,60 100,100 T180,100 Q160,140 120,140 Q80,140 60,120 Q40,120 20,100 Z"
              :fill "url(#flowGrad)"
              :class "floating"}]

      [:circle {:cx 60 :cy 80 :r 8 :fill "#fff" :opacity 0.9 :class "pulsing"}]
      [:circle {:cx 140 :cy 120 :r 6 :fill "#fff" :opacity 0.7 :class "floating"}]
      [:circle {:cx 100 :cy 100 :r 4 :fill "#fff" :opacity 0.8 :class "pulsing"}]]]]

   ;; Stats section
   [:div {:style {:margin-top "30px" :color "white"}}
    [:h3 {:style {:margin-bottom "15px"}} "📊 SVG Performance"]
    [:div {:style {:display "flex" :justify-content "space-around" :text-align "center"}}
     [:div
      [:div {:style {:font-size "2em" :color "#4ecdc4"}} "60"]
      [:div {:style {:font-size "0.9em" :opacity "0.8"}} "FPS"]]
     [:div
      [:div {:style {:font-size "2em" :color "#ffe66d"}} "12"]
      [:div {:style {:font-size "0.9em" :opacity "0.8"}} "Elements"]]
     [:div
      [:div {:style {:font-size "2em" :color "#ff6b6b"}} "3"]
      [:div {:style {:font-size "0.9em" :opacity "0.8"}} "Animations"]]]]

   [:p {:style {:color "white" :opacity "0.8" :margin-top "20px" :font-size "0.9em"}}
    "Smooth SVG animations powered by Joyride Flares ✨"]])

(comment

  ;; Simple greeting panel
  (flare/flare! {:html [:h1 "Hello, Joyride Flares!"]
                 :title "Greeting"
                 :key "greeting"})

  (flare/flare! {:html (create-svg)
                 :title "SVG Shapes"
                 :key "svg-demo"})

  (flare/flare! {:html [:div
                        [:h2 "Sample Data"]
                        (data-table sample-data)]
                 :title "Data Table"
                 :key "data-table"})

  ;; Fancy animated flare with modern design and CSS animations
  (flare/flare! {:html (fancy-flare)
                 :title "🎨 Fancy Joyride Flare"
                 :key "fancy-flare"})

  ;; Fancy SVG flare with animations and beautiful graphics
  (flare/flare! {:html (fancy-svg-flare)
                 :title "🎨 Fancy SVG Showcase"
                 :key "fancy-svg"})

  ;; Sidebar example
  (flare/flare! {:html [:div {:style "padding: 10px;"}
                        [:h3 "Joyride Sidebar"]
                        [:p "This flare appears in the sidebar instead of a separate panel."]
                        [:ul
                         [:li "Useful for quick info"]
                         [:li "Persistent views"]
                         [:li "Space-efficient"]]
                        [:hr]
                        [:small "Use " [:code ":sidebar-panel? true"] " option"]]
                 :title "Sidebar Demo"
                 :sidebar-panel? true})

  (flare/list-active)

  (flare/close! "greeting")

  (flare/list-active)

  (flare/close-all!)

  :rcf)
